name: 'actions-easyconnect'
description: 'run your scripts in easyconnect!'

inputs:
  CLI_OPTS:
    description: '-d {vpnUrl} -u {username} -p {password}'
    required: true
  SCRIPT:
    description: 'Your script'
    required: false
  SLEEP_AFTER_LOGIN:
    description: "How many seconds to sleep after login"
    required: false
    default: 5
  RETRY:
    description: "How many times to retry after error"
    required: false
    default: 1
  EXPECTED_EXIT_CODE:
    description: "Which exception code (not 0) is your expectation"
    required: false
    default: 0
  EXPECTED_IGNORE_CODE:
    description: "Which exception code (not 0) you want to ignore"
    required: false
    default: 255

runs: 
  using: 'composite'
  steps:
    - id: install-easyconnect
      run: sudo bash ${{ github.action_path }}/prerequisite.sh
      shell: bash
    - id: run-it
      shell: bash
      env:
        CLI_OPTS:  ${{ inputs.CLI_OPTS }}
      run: |
        cnt=0
        set +e
        for _retry in {1..${{ inputs.RETRY }}} 
        do
          echo "try_$_retry" `date`
          bash ${{ github.action_path }}/start.sh
          exitCode=$?
          if [[ $exitCode != 0 ]]
          then
            cnt=$(($cnt+1))
            bash ${{ github.action_path }}/stop.sh
            sleep 3
            continue
          fi
          sleep ${{ inputs.SLEEP_AFTER_LOGIN }}
          
          ${{ inputs.SCRIPT }}
          exitCode=$?
          echo "user code exit code: "$exitCode
          if [[ $exitCode == 0 || $exitCode == ${{ inputs.EXPECTED_EXIT_CODE }} ]]
          then
            bash ${{ github.action_path }}/stop.sh
            break
          else
            cnt=$(($cnt+1))  
            bash ${{ github.action_path }}/stop.sh
          fi
        done
        set -e
        if [[ $cnt == ${{ inputs.RETRY }} || $exitCode == ${{ inputs.EXPECTED_EXIT_CODE }} && $exitCode != ${{ inputs.EXPECTED_IGNORE_CODE }}]]
        then
          exit -1
        fi